language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_install:
  - sudo apt-get install -qq vim subversion
  - svn checkout http://v8.googlecode.com/svn/trunk/ ./v8
  - cd v8
  - make dependencies
  - make native
  - sudo cp out/native/d8 /usr/local/bin/v8
  - cd ..
  - rm -rf v8
before_script:
  - npm install -g grunt-cli
  - npm install grunt
  - npm install grunt-contrib-jshint
  - npm install grunt-contrib-nodeunit
  - npm install grunt-contrib-watch
  - npm install grunt-contrib-uglify
  - sleep 5
script: grunt test
