language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_script:
  - npm install -g grunt-cli
  - npm install grunt
  - npm install grunt-contrib-nodeunit
  - sleep 5
script: grunt test
